use_frameworks!
platform :ios, '13.0'

target 'Httper' do
    pod 'Alamofire'
    pod 'ESPullToRefresh'
    pod 'Eureka'
    pod 'Kanna'
    pod 'Kingfisher'
    pod 'M80AttributedLabel'
    pod 'MGFormatter'
    pod 'MGKeyboardAccessory'
    pod 'MGSelector'
    pod 'NVActivityIndicatorView'
    pod 'PagingKit'
    pod 'R.swift'
    pod 'ReachabilitySwift'
    pod 'Reusable'
    pod 'RxAlamofire'
    pod 'RxAlertViewable'
    pod 'RxBinding'
    pod 'RxCocoa'
    pod 'RxController'
    pod 'RxDataSourcesSingleSection'
    pod 'RxFlow'
    pod 'RxKeyboard'
    pod 'RxSwift'
    pod 'SnapKit'
    pod 'SwipeBack'
    pod 'SwiftyUserDefaults'
    pod 'SwiftyJSON'
    pod 'UIGradient'
    pod 'UIImageView+Extension'
    pod 'UITextView+Placeholder'
end
